-- H2 2.3.232;
SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT '4ec9c4daf20ccf20' HASH 'f39095b8b1c171eb1022833c1513fe5051dc0af8f4b17e21af97ef2e1bc27059' ADMIN;         
CREATE SCHEMA IF NOT EXISTS "PROGR" AUTHORIZATION "SA";       
CREATE CACHED TABLE "PROGR"."RESTAURANT"(
    "RESTAURANT_ID" INTEGER NOT NULL,
    "RESTAURANT_NAME" CHARACTER VARYING(60) NOT NULL,
    "RESTAURANT_ADDRESS" CHARACTER VARYING(50) NOT NULL,
    "RESTAURANT_TEL" INTEGER NOT NULL,
    "RESTAURANT_AFM" INTEGER NOT NULL,
    "RESTAURANT_EMAIL" CHARACTER VARYING(50) NOT NULL,
    "RESTAURANT_RATING" FLOAT
);  
ALTER TABLE "PROGR"."RESTAURANT" ADD CONSTRAINT "PROGR"."CONSTRAINT_B" PRIMARY KEY("RESTAURANT_ID");          
-- 0 +/- SELECT COUNT(*) FROM PROGR.RESTAURANT;               
CREATE CACHED TABLE "PROGR"."DISH_CATEGORY"(
    "CATEGORY_ID" INTEGER NOT NULL,
    "CATEGORY_NAME" CHARACTER VARYING(60) NOT NULL
);     
ALTER TABLE "PROGR"."DISH_CATEGORY" ADD CONSTRAINT "PROGR"."CONSTRAINT_BE" PRIMARY KEY("CATEGORY_ID");        
-- 0 +/- SELECT COUNT(*) FROM PROGR.DISH_CATEGORY;            
CREATE CACHED TABLE "PROGR"."DISH"(
    "DISH_ID" INTEGER NOT NULL,
    "RESTAURANT_ID" INTEGER,
    "DISH_NAME" CHARACTER VARYING(60) NOT NULL,
    "DISH_CATEGORY" INTEGER,
    "DISH_PRICE" FLOAT NOT NULL,
    "DISH_IMAGE" CHARACTER VARYING(2083),
    "DISH_DESCRIPTION" CHARACTER VARYING(1000),
    "DISH_AVAILABILITY" INTEGER
);          
ALTER TABLE "PROGR"."DISH" ADD CONSTRAINT "PROGR"."CONSTRAINT_2" PRIMARY KEY("DISH_ID");      
-- 0 +/- SELECT COUNT(*) FROM PROGR.DISH;     
CREATE CACHED TABLE "PROGR"."INGREDIENT"(
    "INGREDIENT_ID" INTEGER NOT NULL,
    "INGREDIENT_NAME" CHARACTER VARYING(60) NOT NULL,
    "INGREDIENT_COST" FLOAT,
    "INGREDIENT_UNIT" CHARACTER VARYING(3) NOT NULL,
    "INGREDIENT_STOCK" FLOAT,
    "INGREDIENT_EXP_DATE" INTEGER
);             
ALTER TABLE "PROGR"."INGREDIENT" ADD CONSTRAINT "PROGR"."CONSTRAINT_1" PRIMARY KEY("INGREDIENT_ID");          
-- 0 +/- SELECT COUNT(*) FROM PROGR.INGREDIENT;               
CREATE CACHED TABLE "PROGR"."DISH_INGRIDIENTS"(
    "DISH_ID" INTEGER,
    "INGREDIENT_ID" INTEGER,
    "INGREDIENT_QUANTITY" FLOAT
);    
-- 0 +/- SELECT COUNT(*) FROM PROGR.DISH_INGRIDIENTS;         
CREATE CACHED TABLE "PROGR"."PURCHASE"(
    "INGREDIENT_ID" INTEGER NOT NULL,
    "PURCHASE_QUANTITY" FLOAT,
    "PURCHASE_COST" FLOAT,
    "PURCHASE_DATE" DATE
);      
ALTER TABLE "PROGR"."PURCHASE" ADD CONSTRAINT "PROGR"."CONSTRAINT_9" PRIMARY KEY("INGREDIENT_ID");            
-- 0 +/- SELECT COUNT(*) FROM PROGR.PURCHASE; 
CREATE CACHED TABLE "PROGR"."RTABLE"(
    "TABLE_ID" INTEGER NOT NULL,
    "TABLE_TOTAL" FLOAT
);          
ALTER TABLE "PROGR"."RTABLE" ADD CONSTRAINT "PROGR"."CONSTRAINT_90" PRIMARY KEY("TABLE_ID");  
-- 0 +/- SELECT COUNT(*) FROM PROGR.RTABLE;   
CREATE CACHED TABLE "PROGR"."REVIEW"(
    "REVIEW_ID" INTEGER NOT NULL,
    "TABLE_ID" INTEGER,
    "REVIEW_RATING" INTEGER,
    "REVIEW_COMMENT" CHARACTER VARYING(200)
);              
ALTER TABLE "PROGR"."REVIEW" ADD CONSTRAINT "PROGR"."CONSTRAINT_8F" PRIMARY KEY("REVIEW_ID"); 
-- 0 +/- SELECT COUNT(*) FROM PROGR.REVIEW;   
CREATE CACHED TABLE "PROGR"."ORDRER"(
    "ORDER_ID" INTEGER NOT NULL,
    "TABLE_ID" INTEGER,
    "DISH_ID" INTEGER,
    "ORDER_DATETIME" TIMESTAMP NOT NULL,
    "ORDER_SUBTOTAL" FLOAT
);            
ALTER TABLE "PROGR"."ORDRER" ADD CONSTRAINT "PROGR"."CONSTRAINT_8B7" PRIMARY KEY("ORDER_ID"); 
-- 0 +/- SELECT COUNT(*) FROM PROGR.ORDRER;   
ALTER TABLE "PROGR"."DISH" ADD CONSTRAINT "PROGR"."CONSTRAINT_20" CHECK("DISH_PRICE" >= CAST(0.0 AS DOUBLE PRECISION)) NOCHECK;               
ALTER TABLE "PROGR"."DISH_INGRIDIENTS" ADD CONSTRAINT "PROGR"."CONSTRAINT_8" CHECK("INGREDIENT_QUANTITY" >= CAST(0.0 AS DOUBLE PRECISION)) NOCHECK;           
ALTER TABLE "PROGR"."PURCHASE" ADD CONSTRAINT "PROGR"."CONSTRAINT_96" CHECK("PURCHASE_QUANTITY" >= CAST(0.0 AS DOUBLE PRECISION)) NOCHECK;    
ALTER TABLE "PROGR"."RTABLE" ADD CONSTRAINT "PROGR"."CONSTRAINT_90A" CHECK("TABLE_TOTAL" >= CAST(0.0 AS DOUBLE PRECISION)) NOCHECK;           
ALTER TABLE "PROGR"."ORDRER" ADD CONSTRAINT "PROGR"."CONSTRAINT_8B72" CHECK("ORDER_SUBTOTAL" >= CAST(0.0 AS DOUBLE PRECISION)) NOCHECK;       
ALTER TABLE "PROGR"."INGREDIENT" ADD CONSTRAINT "PROGR"."CONSTRAINT_109" CHECK("INGREDIENT_STOCK" >= CAST(0.0 AS DOUBLE PRECISION)) NOCHECK;  
ALTER TABLE "PROGR"."PURCHASE" ADD CONSTRAINT "PROGR"."CONSTRAINT_968" CHECK("PURCHASE_COST" >= CAST(0.0 AS DOUBLE PRECISION)) NOCHECK;       
ALTER TABLE "PROGR"."INGREDIENT" ADD CONSTRAINT "PROGR"."CONSTRAINT_10" CHECK("INGREDIENT_COST" >= CAST(0.0 AS DOUBLE PRECISION)) NOCHECK;    
ALTER TABLE "PROGR"."REVIEW" ADD CONSTRAINT "PROGR"."CONSTRAINT_8FE" CHECK(("REVIEW_RATING" >= 0)
    AND ("REVIEW_RATING" <= 5)) NOCHECK;   
ALTER TABLE "PROGR"."DISH" ADD CONSTRAINT "PROGR"."CONSTRAINT_200" CHECK("DISH_AVAILABILITY" IN(1, 2)) NOCHECK;               
ALTER TABLE "PROGR"."INGREDIENT" ADD CONSTRAINT "PROGR"."CONSTRAINT_109C" CHECK("INGREDIENT_EXP_DATE" >= 0) NOCHECK;          
ALTER TABLE "PROGR"."DISH_INGRIDIENTS" ADD CONSTRAINT "PROGR"."CONSTRAINT_8B" FOREIGN KEY("DISH_ID") REFERENCES "PROGR"."DISH"("DISH_ID") NOCHECK;            
ALTER TABLE "PROGR"."ORDRER" ADD CONSTRAINT "PROGR"."CONSTRAINT_8B728" FOREIGN KEY("TABLE_ID") REFERENCES "PROGR"."RTABLE"("TABLE_ID") NOCHECK;               
ALTER TABLE "PROGR"."PURCHASE" ADD CONSTRAINT "PROGR"."CONSTRAINT_968E" FOREIGN KEY("INGREDIENT_ID") REFERENCES "PROGR"."INGREDIENT"("INGREDIENT_ID") NOCHECK;
ALTER TABLE "PROGR"."ORDRER" ADD CONSTRAINT "PROGR"."CONSTRAINT_8B7286" FOREIGN KEY("DISH_ID") REFERENCES "PROGR"."DISH"("DISH_ID") NOCHECK;  
ALTER TABLE "PROGR"."REVIEW" ADD CONSTRAINT "PROGR"."CONSTRAINT_8FE1" FOREIGN KEY("TABLE_ID") REFERENCES "PROGR"."RTABLE"("TABLE_ID") NOCHECK;
ALTER TABLE "PROGR"."DISH_INGRIDIENTS" ADD CONSTRAINT "PROGR"."CONSTRAINT_8B8" FOREIGN KEY("INGREDIENT_ID") REFERENCES "PROGR"."INGREDIENT"("INGREDIENT_ID") NOCHECK;         
ALTER TABLE "PROGR"."DISH" ADD CONSTRAINT "PROGR"."CONSTRAINT_20059" FOREIGN KEY("DISH_CATEGORY") REFERENCES "PROGR"."DISH_CATEGORY"("CATEGORY_ID") NOCHECK;  
ALTER TABLE "PROGR"."DISH" ADD CONSTRAINT "PROGR"."CONSTRAINT_2005" FOREIGN KEY("RESTAURANT_ID") REFERENCES "PROGR"."RESTAURANT"("RESTAURANT_ID") NOCHECK;    
